# Generated by Django 2.2.5 on 2019-10-04 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='foto de perfil')),
                ('gender', models.CharField(blank=True, choices=[('f', 'femenino'), ('m', 'masculino'), ('o', 'otro')], max_length=1, null=True, verbose_name='genero')),
                ('birthday', models.DateField(blank=True, verbose_name='cumpleaños')),
                ('school', models.CharField(blank=True, default='', max_length=255, verbose_name='escuela o facultad')),
                ('major', models.CharField(blank=True, default='', max_length=50, verbose_name='carrera')),
                ('semester', models.CharField(blank=True, default='', max_length=50, verbose_name='semestre')),
                ('preferred_languages', models.CharField(blank=True, default='', max_length=50, verbose_name='lenguajes preferidos')),
                ('bio', models.TextField(verbose_name='biografía')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('personal_website', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
