# Generated by Django 2.2.5 on 2019-10-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='biografía'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro')], max_length=1, null=True, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='semestre'),
        ),
    ]
