# Generated by Django 2.2.5 on 2019-10-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191003_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Personal'),
        ),
    ]
