# Generated by Django 2.2.5 on 2019-10-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191002_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='nombre(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='está activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_editor',
            field=models.BooleanField(default=False, verbose_name='es editor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='es mentor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='es organizador'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='es staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='apellido(s)'),
        ),
    ]
